sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 442390

  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5tMaVaQvyBDPkPwE4Jvz
    access-key-secret: GWMjfyirvUjKmhrs8T2yOXSOp2fore
    bucket-name: sky-fjy-bucket

  redis:
    host: localhost
    port: 6379
    password: 442390
    database: 10